version: '3.11'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cat_api
    ports:
      - "8501:8501"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      - PYTHONPATH=/app
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:14
    container_name: ${POSTGRES_CONTAINER_NAME}
    env_file: .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s


volumes:
  postgres_data:
